#!/bin/bash
 
user="username"
pass="password"
 
login() {
/usr/bin/osascript << EOF
tell application "System Events"
    keystroke "${1}"
    keystroke return
    delay 1
    keystroke "${2}"
    keystroke return
end tell
EOF
}
 
login $user $pass
